Data = {
    1: ['THE AGRA FORT', 'https://en.wikipedia.org/wiki/Agra_Fort', 'UTTAR PRADESH', 'AGRA', '07/02/2026', 1573, 'AGRA AIRPORT', 'https://www.aai.aero/en/node/2901', 'AGRA FORT RAILWAY', 'https://indianrailways.gov.in', 'ALL-DAY', 'THE IMPERIAL, ITC MUGHAL, COURTYARD BY MARRIOTT', 'https://www.tripadvisor.in', 10500, 'A 16th-century Mughal imperial fortress in Agra. It was the main residence of the emperors of the Mughal Dynasty until 1638.', 'Intense Crowds, Touts, Noise, Scams.'],
    2: ['THE TAJ MAHAL', 'https://en.wikipedia.org/wiki/Taj_Mahal', 'UTTAR PRADESH', 'AGRA', '07/02/2026', 1632, 'AGRA AIRPORT', 'https://www.aai.aero', 'AGRA CANTT', 'https://indianrailways.gov.in', '6AM-7PM', 'THE OBEROI AMARVILAS, TAJ HOTEL', 'https://www.tajhotels.com', 15000, 'An ivory-white marble mausoleum on the right bank of the river Yamuna. Built by Shah Jahan for his wife Mumtaz Mahal.', 'Heavy security check, strictly no drones, crowds.'],
    3: ['THE LOTUS TEMPLE', 'https://en.wikipedia.org/wiki/Lotus_Temple', 'DELHI', 'NEW DELHI', '07/02/2026', 1986, 'IGIA DELHI', 'https://www.newdelhiairport.in', 'KALKAJI MANDIR METRO', 'https://www.delhimetrorail.com', '9AM-5PM', 'EROS HOTEL, THE SURYAA', 'https://www.ihg.com', 4500, 'A Bahai House of Worship notable for its flowerlike shape. It has become a prominent attraction in the city.', 'Silence must be maintained, no photography inside.'],
    4: ['THE WILD ASS SANCTUARY', 'https://en.wikipedia.org/wiki/Indian_Wild_Ass_Sanctuary', 'GUJARAT', 'LITTLE RANN OF KUTCH', '07/02/2026', 1972, 'AHMEDABAD AIRPORT', 'https://www.aai.aero', 'DHRANGADHRA RAILWAY', 'https://indianrailways.gov.in', '6AM-6PM', 'RANN RIDERS, DESERT COURTYARD', 'https://www.rannriders.com', 8500, 'The largest wildlife sanctuary in India, home to the endangered Indian Wild Ass.', 'Extreme heat in summer, carry plenty of water.'],
    5: ['THE MATTANCHERRY PALACE', 'https://en.wikipedia.org/wiki/Mattancherry_Palace', 'KERALA', 'KOCHI', '07/02/2026', 1545, 'COCHIN INTERNATIONAL', 'https://cial.aero', 'ERNAKULAM JUNCTION', 'https://indianrailways.gov.in', '10AM-5PM', 'GRAND HYATT, TAJ MALABAR', 'https://www.tajhotels.com', 6000, 'A Portuguese palace popularly known as the Dutch Palace, featuring Kerala murals depicting Hindu temple art.', 'Closed on Fridays, no footwear inside galleries.'],
    6: ['LE CORBUSIER ARCHITECTURAL WORK', 'https://en.wikipedia.org/wiki/The_Architectural_Work_of_Le_Corbusier', 'CHANDIGARH', 'CHANDIGARH', '07/02/2026', 1950, 'CHANDIGARH AIRPORT', 'https://www.aai.aero', 'CHANDIGARH JUNCTION', 'https://indianrailways.gov.in', '9AM-5PM', 'JW MARRIOTT, TAJ CHANDIGARH', 'https://www.marriott.com', 9000, 'The Capitol Complex in Chandigarh is a UNESCO site representing the modern movement in architecture.', 'Prior permission needed for the Capitol Complex.'],
    7: ['THE GREAT HIMALAYAN NATIONAL PARK', 'https://en.wikipedia.org/wiki/Great_Himalayan_National_Park', 'HIMACHAL PRADESH', 'KULLU', '07/02/2026', 1984, 'KULLU MANALI AIRPORT', 'https://www.aai.aero', 'JOGINDER NAGAR', 'https://indianrailways.gov.in', 'ALL-DAY', 'THE RAJU COTTAGE, FOREST GUEST HOUSE', 'https://www.himachaltourism.gov.in', 12000, 'A high altitude park with diverse flora and fauna, including the elusive Snow Leopard.', 'Steep treks, unpredictable weather, permit required.'],
    8: ['THE WESTERN GHATS', 'https://en.wikipedia.org/wiki/Western_Ghats', 'MAHARASHTRA/KARNATAKA/KERALA', 'MULTIPLE', '07/02/2026', 2012, 'MUMBAI/BANGALORE AIRPORT', 'https://www.aai.aero', 'MULTIPLE', 'https://indianrailways.gov.in', 'ALL-DAY', 'VIVANTA BY TAJ, STERLING RESORTS', 'https://www.sterlingholidays.com', 18000, 'One of the worlds ten hottest biodiversity hotspots, older than the Himalayas.', 'Leeches during monsoon, dense forests, stay on trails.'],
    9: ['THE RED FORT', 'https://en.wikipedia.org/wiki/Red_Fort', 'DELHI', 'OLD DELHI', '07/02/2026', 1639, 'IGIA DELHI', 'https://www.newdelhiairport.in', 'OLD DELHI RAILWAY', 'https://indianrailways.gov.in', '9:30AM-4:30PM', 'THE MAIDENS HOTEL, ITC MAURYA', 'https://www.oberoihotels.com', 8000, 'A historic fort that served as the main residence of Mughal Emperors for nearly 200 years.', 'Closed on Mondays, extremely crowded, light show at night.'],
    10: ['THE ROCK SHELTERS OF BHIMBETKA', 'https://en.wikipedia.org/wiki/Rock_Shelters_of_Bhimbetka', 'MADHYA PRADESH', 'RAISEN', '07/02/2026', 2003, 'BHOPAL AIRPORT', 'https://www.aai.aero', 'BHOPAL JUNCTION', 'https://indianrailways.gov.in', '7AM-6PM', 'JEHAN NUMA PALACE, COURTYARD BY MARRIOTT', 'https://www.marriott.com', 7500, 'Archaeological site exhibiting the earliest traces of human life on the Indian subcontinent.', 'Remote area, hire a guide for historical context.'],
    11: ['THE MOUNTAIN RAILWAYS OF INDIA', 'https://en.wikipedia.org/wiki/Mountain_Railways_of_India', 'WB/TN/HP', 'MULTIPLE', '07/02/2026', 1999, 'BAGDOGRA/COIMBATORE', 'https://www.aai.aero', 'DARJEELING/OOTY/KALKA', 'https://indianrailways.gov.in', 'SCHEDULE-BASED', 'WINDAMERE HOTEL, SAVOY OOTY', 'https://www.tajhotels.com', 14000, 'Includes Darjeeling Himalayan Railway, Nilgiri Mountain Railway, and Kalka-Shimla Railway.', 'Book tickets months in advance, landslides in monsoon.'],
    12: ['THE QUTB MINAR', 'https://en.wikipedia.org/wiki/Qutb_Minar', 'DELHI', 'MEHRAULI', '07/02/2026', 1192, 'IGIA DELHI', 'https://www.newdelhiairport.in', 'QUTUB MINAR METRO', 'https://www.delhimetrorail.com', '7AM-9PM', 'THE LODHI, HILTON GARDEN INN', 'https://www.hilton.com', 5000, 'A 73-metre tall tapering tower and a UNESCO World Heritage Site.', 'No climbing the tower, high summer heat.'],
    13: ['THE SUNDARBANS NATIONAL PARK', 'https://en.wikipedia.org/wiki/Sundarbans_National_Park', 'WEST BENGAL', '24 PARGANAS', '07/02/2026', 1987, 'KOLKATA AIRPORT', 'https://www.aai.aero', 'CANNING RAILWAY', 'https://indianrailways.gov.in', '8AM-6PM', 'SUNDARBAN TIGER CAMP', 'https://www.sundarbantigercamp.com', 16000, 'World largest mangrove forest and home to the Royal Bengal Tiger.', 'Boat travel only, watch out for crocodiles and tigers.'],
    14: ['THE HAMPI MONUMENTS', 'https://en.wikipedia.org/wiki/Hampi', 'KARNATAKA', 'HAMPI', '07/02/2026', 1986, 'HUBLI AIRPORT', 'https://www.aai.aero', 'HOSAPETE JUNCTION', 'https://indianrailways.gov.in', '6AM-6PM', 'EVOLVE BACK, HYATT PLACE', 'https://www.evolveback.com', 11000, 'Ruins of the Vijayanagara Empire capital, featuring stunning Dravidian temples.', 'Vast area, hire a bicycle, dress conservatively.'],
    15: ['THE MAHABALIPURAM MONUMENTS', 'https://en.wikipedia.org/wiki/Mahabalipuram', 'TAMIL NADU', 'CHENGALPATTU', '07/02/2026', 1984, 'CHENNAI INTERNATIONAL', 'https://www.aai.aero', 'CHENGALPATTU JUNCTION', 'https://indianrailways.gov.in', '6AM-6PM', 'RADISSON BLU RESORT, TAJ FISHERMANS COVE', 'https://www.tajhotels.com', 9500, 'A collection of 7th- and 8th-century religious monuments including the Shore Temple.', 'Humid coastal weather, local monkeys can be aggressive.'],
    16: ['THE SUN TEMPLE KONARK', 'https://en.wikipedia.org/wiki/Konark_Sun_Temple', 'ODISHA', 'PURI', '07/02/2026', 1984, 'BHUBANESWAR AIRPORT', 'https://www.aai.aero', 'PURI RAILWAY', 'https://indianrailways.gov.in', '6AM-8PM', 'MAYFAIR WAVES, THE CHARIOT', 'https://www.mayfairhotels.com', 8000, 'A 13th-century Sun Temple shaped like a giant chariot with carved stone wheels.', 'Intense sun, hire a government approved guide.'],
    17: ['THE ELLORA CAVES', 'https://en.wikipedia.org/wiki/Ellora_Caves', 'MAHARASHTRA', 'AURANGABAD', '07/02/2026', 1983, 'AURANGABAD AIRPORT', 'https://www.aai.aero', 'AURANGABAD RAILWAY', 'https://indianrailways.gov.in', '6AM-6PM', 'VIVANTA, WELCOMHOTEL RAMA INTERNATIONAL', 'https://www.itchotels.com', 9000, 'One of the largest rock-cut monastery-temple cave complexes in the world.', 'Closed on Tuesdays, lots of walking and steps.'],
    18: ['THE AJANTA CAVES', 'https://en.wikipedia.org/wiki/Ajanta_Caves', 'MAHARASHTRA', 'AURANGABAD', '07/02/2026', 1983, 'AURANGABAD AIRPORT', 'https://www.aai.aero', 'JALGAON JUNCTION', 'https://indianrailways.gov.in', '9AM-5PM', 'VIVANTA, HOTEL AJANTA AMBASSADOR', 'https://www.tajhotels.com', 9000, 'Buddhist cave monuments dating from the 2nd century BCE to 480 CE.', 'Closed on Mondays, no flash photography.'],
    19: ['THE GOLDEN TEMPLE', 'https://en.wikipedia.org/wiki/Golden_Temple', 'PUNJAB', 'AMRITSAR', '07/02/2026', 1577, 'AMRITSAR AIRPORT', 'https://www.aai.aero', 'AMRITSAR JUNCTION', 'https://indianrailways.gov.in', 'ALL-DAY', 'HYATT REGENCY, TAJ SWARNA', 'https://www.tajhotels.com', 7000, 'The preeminent spiritual site of Sikhism, also known as Sri Harmandir Sahib.', 'Cover your head, remove shoes, photography limited.'],
    20: ['THE CHURCHES AND CONVENTS OF GOA', 'https://en.wikipedia.org/wiki/Churches_and_Convents_of_Goa', 'GOA', 'OLD GOA', '07/02/2026', 1986, 'GOA INTERNATIONAL', 'https://www.aai.aero', 'MADGAON JUNCTION', 'https://indianrailways.gov.in', '7:30AM-6:30PM', 'W GOA, TAJ EXOTICA', 'https://www.marriott.com', 13000, 'A set of religious monuments in Old Goa, the former capital of Portuguese India.', 'Dress modestly for active churches, parking can be far.']
}
print("\t\t HERITAGE SITE LIST", "\n \n The table lists Serial No, Name, State, City, Date Estabilished, Closest Airport, Closest Railway, Touring Times, Close hotels from IHG, Average tourism rates and a desc")
for x in Data:
    print(x, '-\t', Data[x][0], Data[x][2], '-\t', Data[x][3], '-\t', Data[x][5], '-\t', Data[x][6], '-\t', Data[x][8], '-\t', Data[x][10], '-\t', Data[x][11], '-\t', Data[x][13], '-\t', Data[x][14], '\n\n\n')
